name: Assign to snapshot project

on:
  issues:
    types: [labeled]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'snapshot'
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: Snapshot+Restore
          column: To do
          repo-token: ${{ secrets.GITHUB_TOKEN }}
